### ISSUE TITLE
Using MIBs in order to use short names for objects over numeric dot notation for OIDs

### ISSUE THREAD

**Issue by yeongsheng-tan** [jonnystorm/snmp-mib-elixir#2]
Is there a way to perform NetSNMP.get or table or walk via short names over the numeric dot notation OIDs?

**Comment by jonnystorm** [comment]
Thanks for your recent contributions!

Unfortunately, resolving MIB names is not yet possible. The private function `NetSNMP.objects_to_oids/1` could be changed to resolve a name to an OID without affecting code that depends on it, but there may be some assumptions elsewhere that would require further changes. Perhaps a new field in the `%SNMPMIB.Object{}` struct would be sufficient.

Ultimately, I lament producing a wrapper for netsnmp because catching its myriad errors requires a lot of code for little gain. I further believe snmp-mib-elixir was ill conceived, as parsing the actual MIBs to generate such code would be far less error prone, and this would allow you to use short names freely--and without more code.

To help you now, here is a snippet demonstrating how to resolve MIB names with Erlang's `:snmpm` module: [https://gist.github.com/jonnystorm/7136bff23cca0f84219d6cd4cdaeabfc](https://gist.github.com/jonnystorm/7136bff23cca0f84219d6cd4cdaeabfc). Bear in mind that the procedure to do this is fraught with peril--which is why I avoided it--but I think this is a better approach.

My next effort should be to put Elixir scar tissue around Erlang's SNMP libraries, and when this is done, I'll be happy to announce net-snmp-elixir's replacement. Until then, I'll continue to accept pull requests, but I can't justify writing more features for snmp-mib-elixir; to me, it's a dead end.
